In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("Pokemon.csv")

In [3]:
df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [61]:
df["Legendary"].value_counts()

False    735
True      65
Name: Legendary, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64 
 5   HP          800 non-null    int64 
 6   Attack      800 non-null    int64 
 7   Defense     800 non-null    int64 
 8   Sp. Atk     800 non-null    int64 
 9   Sp. Def     800 non-null    int64 
 10  Speed       800 non-null    int64 
 11  Generation  800 non-null    int64 
 12  Legendary   800 non-null    bool  
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB


In [7]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()

In [12]:
new_df = df.copy()

In [13]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
label.fit(new_df['Type 1'])
new_df['Type 1'] = label.transform(new_df['Type 1'])

In [51]:
X = new_df.drop(["Name", "Type 2", "Legendary", "Total", "#"], axis=1)
y = new_df["Legendary"]
y = label.fit_transform(y)


In [31]:
X

Type 1  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0         9  45      49       49       65       65     45           1
1         9  60      62       63       80       80     60           1
2         9  80      82       83      100      100     80           1
3         9  80     100      123      122      120     80           1
4         6  39      52       43       60       50     65           1
..      ...  ..     ...      ...      ...      ...    ...         ...
795      15  50     100      150      100      150     50           6
796      15  50     160      110      160      110    110           6
797      14  80     110       60      150      130     70           6
798      14  80     160       60      170      130     80           6
799       6  80     110      120      130       90     70           6

[800 rows x 8 columns]

In [11]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,stratify=y, random_state=101)

In [35]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scale = MinMaxScaler()

In [63]:
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [64]:
import tensorflow as tf
import keras


model = keras.Sequential([
    keras.layers.Dense(8, input_shape=(8,), activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(1 ,activation='sigmoid')
])

model.compile(optimizer='adam', 
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [65]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
17/17 [==============================] - 2s 3ms/step - loss: 0.6841 - accuracy: 0.7351
Epoch 2/5
17/17 [==============================] - 0s 5ms/step - loss: 0.6586 - accuracy: 0.9067
Epoch 3/5
17/17 [==============================] - 0s 5ms/step - loss: 0.6264 - accuracy: 0.9179
Epoch 4/5
17/17 [==============================] - 0s 5ms/step - loss: 0.5823 - accuracy: 0.9179
Epoch 5/5
17/17 [==============================] - 0s 5ms/step - loss: 0.5252 - accuracy: 0.9179


In [66]:
yp = model.predict(X_test)

9/9 [==============================] - 0s 3ms/step


In [56]:
yp[:5]

array([[0.16247053],
       [0.15442   ],
       [0.1512571 ],
       [0.16817704],
       [0.2155951 ]], dtype=float32)

In [67]:
pred = []

for element in yp:
    if element > 0.5:
        pred.append(1)
    else:
        pred.append(0)

In [58]:
pred[:5]

[0, 0, 0, 0, 0]

In [60]:
y_test[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [68]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96       264
           1       0.00      0.00      0.00         0

    accuracy                           0.92       264
   macro avg       0.50      0.46      0.48       264
weighted avg       1.00      0.92      0.96       264



c:\Users\Oloye\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Oloye\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Oloye\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, le

In [69]:
confusion_matrix(pred,y_test)

array([[243,  21],
       [  0,   0]], dtype=int64)